navikt/ft-inntektsmelding-frontend

app/package-lock.json
app/package.json
app/src/api/mutations.ts
app/src/api/queries.ts
app/src/features/skjema-moduler/Inntekt.tsx
app/src/features/skjema-moduler/PersonOgSelskapsInformasjonSeksjon.tsx
app/src/routes/ny.$id.tsx
app/src/types/api-models.ts
app/src/views/ny-inntektsmelding/NyInntektsmelding.tsx

Tar ibruk forespørselId fra url og gjør kall for å hente data dynamisk

Bruk forespørselId og hent data dynamisk

---

app/README.md
app/src/features/rot-layout/RotLayout.tsx
app/src/routes/ny.$id.oppsummering.tsx
app/src/views/oppsummering/Oppsummering.tsx

Trenger fortsatt støtte for forskjellige ting og tang, men et greit utgangspunkt.

Legg til oppsummeringssteg, rent visuelt

---

app/src/features/skjema-moduler/Fremgangsindikator.tsx
app/src/features/skjema-moduler/Inntekt.tsx
app/src/features/skjema-moduler/PersonOgSelskapsInformasjonSeksjon.tsx
app/src/routes/$id.inntekt-og-refusjon.tsx
app/src/routes/__root.tsx
app/src/utils.ts
app/src/views/oppsummering/Oppsummering.tsx

En haug med småforbedringer rundt om

Forbedringer oppsummering

---

app/src/features/InformasjonsseksjonMedKilde.tsx
app/src/features/skjema-moduler/PersonOgSelskapsInformasjonSeksjon.tsx

Denne PRen fikser en liten layoutbug der ting ikke så så fint ut på mobil.

Fiks en layoutbug

---

app/src/features/skjema-moduler/Inntekt.tsx

Legg til beregningstekster

---

app/src/features/InntektsmeldingSkjemaState.tsx
app/src/main.tsx
app/src/routes/__root.tsx
app/src/views/ny-inntektsmelding/NyInntektsmelding.tsx

Denne PRen endrer slik at 404-ruten vår er får en maksbredde og blir midtstilt.

Sentrer 404-viewet

---

app/src/api/queries.ts
app/src/features/InntektsmeldingSkjemaState.tsx
app/src/types/api-models.ts
app/src/views/kvittering/Kvittering.tsx
app/src/views/shared/Skjemaoppsummering.tsx
app/src/views/vis/VisInntektsmelding.tsx

Denne PRen legger til støtte for å laste ned PDF-versjon av inntektsmeldingen, både på kvitteringssiden og i "vis inntektsmelding" viewet.

Last ned PDF

---

app/src/views/kvittering/Kvittering.tsx

Det var noen gjenstående todos og placeholder i kvitteringen, som denne PRen fikser.

Legg til ytelsesnavn og fullt navn i kvitteringen

---

README.md
app/README.md

Readme-ene våre hadde råtna litt på rot. Denne PRen forbedrer dem litt.

Forbedre readmes

---

app/src/features/refusjon-omsorgspenger-arbeidsgiver/Steg2AnsattOgArbeidsgiver.tsx
app/src/features/refusjon-omsorgspenger-arbeidsgiver/api/queries.ts
app/src/features/skjema-moduler/Inntekt.tsx
app/src/utils.ts

Denne PRen introduserer henting av persondata når man skriver inn et fødselsnummer. Det er også lagt til støtte for flere forskjellige arbeidsforhold.
Endepunktet finnes ikke enn så lenge, men det ser i alle fall slik ut (inkl feilhåndtering) når man skriver inn 11 siffer:

Hent arbeidsforhold og persondata

---

app/src/features/refusjon-omsorgspenger-arbeidsgiver/Steg5Oppsummering.tsx
app/src/features/refusjon-omsorgspenger-arbeidsgiver/Steg6Kvittering.tsx
app/src/features/skjema-moduler/Inntekt.tsx
app/src/features/skjema-moduler/Naturalytelser.tsx
app/src/features/skjema-moduler/PersonOgSelskapsInformasjonSeksjon.tsx
app/src/features/skjema-moduler/UtbetalingOgRefusjon.tsx
app/src/routes/$id.inntekt-og-refusjon.tsx
app/src/utils.ts
app/src/views/kvittering/Kvittering.tsx
app/src/views/ny-inntektsmelding/NyInntektsmelding.tsx
app/src/views/shared/Skjemaoppsummering.tsx
app/src/views/vis/VisInntektsmelding.tsx

Fiks en haug med mindre greier som kom opp i en gjennomgang

---

app/src/features/InntektsmeldingSkjemaState.tsx
app/src/features/skjema-moduler/Inntekt.tsx
app/src/features/skjema-moduler/Naturalytelser.tsx
app/src/features/skjema-moduler/PersonOgSelskapsInformasjonSeksjon.tsx
app/src/features/skjema-moduler/UtbetalingOgRefusjon.tsx
app/src/routes/$id.inntekt-og-refusjon.tsx
app/src/types/api-models.ts
app/src/utils.ts
app/src/views/kvittering/Kvittering.tsx
app/src/views/ny-inntektsmelding/NyInntektsmelding.tsx
app/src/views/ny-inntektsmelding/OpplysningerContext.tsx
app/src/views/oppsummering/Oppsummering.tsx
app/src/views/shared/Skjemaoppsummering.tsx

Denne PRen fikser en haug med smågreier, som jeg kommenterer i selve PRen istedenfor å gå gjennom i oppsummeringen.

Småfiks-PR

---

app/src/features/skjema-moduler/Inntekt.tsx

Det skal være mulig å oppgi at korrigert inntekt er 0.

Tillat 0 i korrigert inntekt

---

app/src/features/inntektsmelding/InntektsmeldingRootLayout.tsx
app/src/features/inntektsmelding/OpplysningerContext.tsx
app/src/features/inntektsmelding/Skjemaoppsummering.tsx
app/src/features/inntektsmelding/Steg1DineOpplysninger.tsx
app/src/features/inntektsmelding/Steg2InntektOgRefusjon.tsx
app/src/features/inntektsmelding/Steg3Oppsummering.tsx
app/src/features/inntektsmelding/Steg4Kvittering.tsx
app/src/features/inntektsmelding/useOpplysninger.tsx
app/src/features/refusjon-omsorgspenger-arbeidsgiver/Steg2AnsattOgArbeidsgiver.tsx
app/src/features/skjema-moduler/Inntekt.tsx
app/src/features/skjema-moduler/Naturalytelser.tsx
app/src/features/skjema-moduler/UtbetalingOgRefusjon.tsx
app/src/types/api-models.ts
app/src/utils.ts

Denne PRen fikser endel smågreier jeg kom over under testing!

Diverse småforbedringer

---

app/src/features/refusjon-omsorgspenger-arbeidsgiver/Steg3Omsorgsdager.tsx
app/src/features/skjema-moduler/Inntekt.tsx
app/src/features/skjema-moduler/Naturalytelser.tsx
app/src/features/skjema-moduler/UtbetalingOgRefusjon.tsx

Gikk gjennom noen av skissene til Lise, og oppdaterte et par smågreier her og der.
De største endringene er:
- redesign av endringsårsak-brukergrensesnittet
- redesign av naturalytelser
- bruk av vanlig alert istedenfor inline alert for en av warningsa.
- bruk medium knapper der vi før har brukt small
- små tekstendringer her og der

Designtweaks fra lise

---

app/src/features/inntektsmelding/Steg2InntektOgRefusjon.tsx
app/src/features/refusjon-omsorgspenger-arbeidsgiver/Steg2AnsattOgArbeidsgiver.tsx
app/src/features/refusjon-omsorgspenger-arbeidsgiver/Steg3Omsorgsdager.tsx
app/src/features/refusjon-omsorgspenger-arbeidsgiver/Steg4Refusjon.tsx
app/src/features/skjema-moduler/Inntekt.tsx

Denne PRen retter opp i litt mobilbugs, litt valideringsbugs og en avhengighets i endringsårsaker-komponenten som kræsja hele sulamitten.

Småfiks på refusjonsflyten

---

app/src/features/refusjon-omsorgspenger-arbeidsgiver/RefusjonOmsorgspengerArbeidsgiverForm.tsx
app/src/features/refusjon-omsorgspenger-arbeidsgiver/Steg3Omsorgsdager.tsx
app/src/features/refusjon-omsorgspenger-arbeidsgiver/Steg5Oppsummering.tsx

Vi ønsker å spørre arbeidsgiveren hva normalarbeidstiden er på de dagene det er fravær deler av dagen, så vi kan beregne hvor mye man skal få igjen.

Legg til normalarbeidstid

---

app/src/features/skjema-moduler/Inntekt.tsx

Mer språklig småflikk

---

app/src/features/inntektsmelding/Steg1DineOpplysninger.tsx
app/src/features/inntektsmelding/Steg2InntektOgRefusjon.tsx
app/src/features/inntektsmelding/Steg4Kvittering.tsx
app/src/features/refusjon-omsorgspenger-arbeidsgiver/Steg1Intro.tsx
app/src/features/refusjon-omsorgspenger-arbeidsgiver/Steg3Omsorgsdager.tsx
app/src/features/skjema-moduler/Inntekt.tsx
app/src/features/skjema-moduler/UtbetalingOgRefusjon.tsx

Nav har endret navn fra NAV til Nav, og man må dermed tilpasse stavemåten i vår løsning også.

Endre fra NAV til Nav i alle tekster

---

app/src/features/refusjon-omsorgspenger-arbeidsgiver/Steg2AnsattOgArbeidsgiver.tsx
app/src/features/refusjon-omsorgspenger-arbeidsgiver/Steg3Omsorgsdager.tsx

Fikset litt design-issues, og la til en validering på at man har fylt ut minst ett fravær

Design-flikking

---

app/src/features/InntektsmeldingSkjemaState.tsx
app/src/features/skjema-moduler/Inntekt.tsx
app/src/features/skjema-moduler/Naturalytelser.tsx
app/src/features/skjema-moduler/UtbetalingOgRefusjon.tsx
app/src/settOppGrafanaFaro.ts
app/tests/e2e/ny-inntektsmelding-valideringer.spec.tsx
app/tests/mocks/opplysninger.ts
app/tests/mocks/send-inntektsmelding.ts
app/tests/mocks/utils.ts

Laget en svær test som prøver ut det meste av valideringer jeg kunne komme på.
Spørsmålet er hvordan dette burde struktureres. I cypress (som er hva jeg har brukt før) anbefales det egentlig med lange specs.
Kanskje det naturlige hadde vært å dratt ut validering i egne tester per modul? f.eks UtbetalingOgRefusjon-validering.spec og naturalytelse-validering.spec?
Åpen for forslag og gode practices her. Første gang med playwright for meg. Første inntrykket var veldig bra!

Skriv litt tester

---

app/index.html
app/src/features/rot-layout/RotLayout.tsx
app/src/features/skjema-moduler/Inntekt.tsx
app/src/features/skjema-moduler/Naturalytelser.tsx
app/src/features/skjema-moduler/UtbetalingOgRefusjon.tsx

Mens vi gikk gjennom og fylte ut tilgjengelighetserklæringen kom vi over noen mindre feil. Denne PRen retter disse.

Forbedringer av universell utforming

---

.deploy/k9/naiserator.yaml
.github/workflows/build.yml

Denne PRen prodsetter k9-im-dialog, slik at alt er klart til lansering i morgen.
@johannbm tar du en titt på at jeg har husket på alt?

K9 i prod innen lunsj

---

.cursorrules

Denne PRen legger til en spesiell fil for [Cursor](https://www.cursor.com/), som hjelper AI-verktøy å gi gode råd basert på kodebasen vår. Det fungerer også fint som kontekst for nye utviklere.

Legg til en første iterasjon på .cursorrules
